server:
  port: 8080

sms:
  mockServiceId:
    unifonic:
      url: https://el.cloud.unifonic.com/rest/SMS/messages
      appSid: test
      senderId: Araz
    t2:
      password: test
      sender: Test
      username: araz.badalov@gmail
      url: https://stopservices.rich.sa/RiCHClientServiceREST.svc/SendSmsConfirmationPost

spring:
  datasource:
    username: sa
    password: 12345678
    url: jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=false
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect

logging:
  config: classpath:logback-local.xml