server:
  port: 8080

sms:
  mockServiceId:
    unifonic:
      url: https://el.cloud.unifonic.com/rest/SMS/messages
      appSid: test
      senderId: Araz
    t2:
      password: test
      sender: Test
      username: araz.badalov@gmail
      url: https://stopservices.rich.sa/RiCHClientServiceREST.svc/SendSmsConfirmationPost

logging:
  level:
    com:
      takamol:
        qiwa:
          sms:
            gateway:
              util:
                LoggingRequestInterceptor: INFO
  config: classpath:logback-spring.xml

spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=master;encrypt=false
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect
  application:
    name: badalov-sms

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
